### ISSUE TITLE
from_fix node keeps crashing

### ISSUE THREAD

**Issue by pmukherj** [clearpathrobotics/enu#7]
from_fix node keeps crashing and/or resetting. Problem is extra prevalent on mini-ITX computers. Example bag is available.
![screenshot from 2013-10-01 23 42 19](https://f.cloud.github.com/assets/2953131/1251061/b137e0b2-2b14-11e3-99af-c730d12cc5a4.png)

**Comment by mikepurvis** [comment]
I believe this was due to the underlying swiftnav library being built with very aggressive CPU optimizations—I've changed the swiftnav release repo to remove these optimizations from the deb and rereleased.

See: https://github.com/clearpath-gbp/libswiftnav-release/blob/patches/release/hydro/swiftnav/0002-Avoid-using-architecture-specific-optimizations-in-t.patch
